name: Self-hosted CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

  make-tests:
    name: Make tests
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: ps
      run: ps aeuxwww
    - name: env
      run: env
